#include "vlak_levels.h"
#include "vlak_elements.h"

int vlak_level_get_element_pos(vlak_level_t* level, vlak_element_t element)
{
    for (int tile = 0; tile < LEVEL_LEN; tile++)
    {
        vlak_element_t tile_id = level->content[tile];

        if (tile_id == element)
        {
            return tile;
        }
    }

    return -1;
}

static vlak_level_t LEVEL_0_DEMO = {
    .name = "DEMO",
    .content = {
KRY,  0,  0,  0,KRY,STO,  0,  0,  0,  0,  0,  0,KOR,  0,  0,JAB,  0,  0,  0,JAB,
KRY,  0,  0,  0,KRY,STO,  0,  0,  0,  0,  0,KOR,  0,KOR,  0,JAB,  0,  0,JAB,  0,
KRY,  0,  0,  0,KRY,STO,  0,  0,  0,  0,KOR,  0,  0,  0,KOR,JAB,  0,JAB,  0,  0,
KRY,  0,  0,  0,KRY,STO,  0,  0,  0,  0,KOR,  0,  0,  0,KOR,JAB,JAB,  0,  0,  0,
KRY,  0,  0,  0,KRY,STO,  0,  0,  0,  0,KOR,KOR,KOR,KOR,KOR,JAB,  0,JAB,  0,  0,
  0,KRY,  0,KRY,  0,STO,  0,  0,  0,  0,KOR,  0,  0,  0,KOR,JAB,  0,  0,JAB,  0,
  0,  0,KRY,  0,  0,STO,STO,STO,STO,STO,KOR,  0,  0,  0,KOR,JAB,  0,  0,  0,JAB,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_1_GOLEM = {
    .name = "GOLEM",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,KRY,KRY,KRY,KRY,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,VRA,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_2_KRONE = {
    .name = "KRONE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KOR,  0,KOR,  0,KOR,  0,KOR,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KOR,KOR,KOR,KOR,KOR,KOR,KOR,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KOR,KOR,KOR,KOR,KOR,KOR,KOR,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KOR,KOR,KOR,KOR,KOR,KOR,KOR,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_3_MYDLO = {
    .name = "MYDLO",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,KRY,KRY,KRY,  0,  0,  0,  0,ZED,  0,  0,  0,STO,  0,STO,  0,  0,  0,ZED,
ZED,  0,KRY,KOR,KRY,  0,  0,  0,  0,ZED,  0,  0,STO,  0,STO,  0,STO,  0,  0,ZED,
ZED,  0,KRY,KRY,KRY,  0,  0,  0,  0,ZED,  0,  0,  0,STO,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,  0,  0,  0,  0,VRA,  0,  0,STO,  0,STO,  0,STO,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,STO,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,LOK,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_4_LEDEN = {
    .name = "LEDEN",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,KRY,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,  0,  0,  0,JAB,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,JAB,JAB,JAB,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,JAB,JAB,STO,JAB,JAB,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,ZED,  0,  0,JAB,JAB,STO,ZED,STO,JAB,JAB,  0,  0,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,  0,JAB,JAB,STO,JAB,ZED,JAB,STO,JAB,JAB,  0,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,JAB,JAB,STO,JAB,JAB,JAB,JAB,JAB,STO,JAB,JAB,ZED,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_5_STROP = {
    .name = "STROP",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,KRA,  0,KRA,  0,KRA,  0,ZED,  0,  0,KRA,  0,KRA,  0,KRA,  0,  0,ZED,
ZED,LOK,  0,  0,KRA,  0,KRA,  0,  0,ZED,  0,  0,  0,KRA,  0,KRA,  0,  0,  0,ZED,
ZED,  0,  0,KRA,  0,KRA,  0,KRA,  0,ZED,  0,  0,KRA,  0,KRA,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,KRA,  0,KRA,  0,  0,ZED,  0,  0,  0,KRA,  0,KRA,  0,  0,  0,ZED,
VRA,  0,  0,KRA,  0,KRA,  0,KRA,  0,ZED,  0,  0,KRA,  0,KRA,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,KOR,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_6_LILIE = {
    .name = "LILIE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,KOR,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,TRE,TRE,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,TRE,TRE,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,  0,TRE,TRE,KOR,TRE,TRE,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,TRE,TRE,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,TRE,TRE,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,TRE,TRE,TRE,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,KRY,  0,  0,  0,ZED,
VRA,  0,  0,STO,STO,STO,STO,STO,STO,STO,STO,STO,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_7_RYBKA = {
    .name = "RYBKA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,KRY,  0,  0,  0,STO,STO,STO,  0,  0,  0,KRA,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,ZED,  0,  0,STO,  0,RYB,  0,STO,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,KRY,  0,  0,STO,RYB,  0,RYB,STO,  0,  0,  0,KRA,  0,KRA,  0,ZED,
ZED,  0,  0,  0,ZED,  0,  0,STO,  0,RYB,  0,STO,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,KRY,  0,  0,STO,RYB,  0,RYB,STO,  0,  0,KRA,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,ZED,  0,  0,STO,  0,ZED,  0,STO,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,KRY,  0,  0,  0,STO,ZED,STO,  0,  0,  0,  0,KRA,  0,KRA,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_8_KLAUN = {
    .name = "KLAUN",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,ZED,ZED,ZED,  0,ZED,ZED,ZED,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,  0,  0,STO,  0,STO,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,LOK,  0,KRY,  0,ZED,  0,JAB,  0,ZIR,  0,JAB,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,  0,  0,STO,  0,STO,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,  0,  0,  0,RYB,  0,  0,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,  0,STO,  0,  0,  0,STO,  0,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,VRA,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_9_BRAUN = {
    .name = "BRAUN",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,JAB,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,STO,STO,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,KRY,KRY,  0,  0,ZED,  0,ZMR,ZMR,  0,ZED,  0,  0,KRY,KRY,  0,  0,ZED,
ZED,  0,KRY,KRY,KRY,KRY,  0,ZED,  0,ZMR,ZMR,  0,ZED,  0,KRY,KRY,KRY,KRY,  0,ZED,
ZED,  0,KRY,KRY,KRY,KRY,  0,ZED,  0,ZMR,ZMR,  0,ZED,  0,KRY,KRY,KRY,KRY,  0,ZED,
ZED,  0,  0,KRY,KRY,  0,  0,ZED,  0,ZMR,ZMR,  0,ZED,  0,  0,KRY,KRY,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,ZED,  0,  0,ZED,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_10_WHITE = {
    .name = "WHITE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,STO,  0,  0,  0,ZMR,  0,ZMR,  0,ZMR,  0,  0,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,  0,  0,  0,ZMR,  0,ZMR,  0,  0,  0,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,  0,  0,  0,KRY,  0,  0,  0,ZED,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,  0,  0,  0,KOR,  0,  0,  0,ZED,  0,STO,  0,  0,  0,ZED,
ZED,LOK,  0,RYB,  0,ZED,  0,  0,ZED,VRA,ZED,  0,  0,ZED,  0,ZIR,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,KRA,  0,ZED,DOR,ZED,  0,KRA,ZED,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,  0,  0,ZED,KRY,ZED,  0,  0,ZED,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,  0,  0,ZED,KRY,ZED,  0,  0,ZED,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,ZED,  0,  0,ZED,KRY,ZED,  0,  0,ZED,  0,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,STO,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_11_MOUSE = {
    .name = "MOUSE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,RYB,  0,ZED,ZED,  0,RYB,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,  0,POC,POC,  0,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,POC,POC,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,POC,POC,  0,  0,ZED,
ZED,  0,  0,POC,POC,  0,ZED,  0,  0,KOR,KOR,  0,  0,ZED,  0,POC,POC,  0,  0,ZED,
ZED,LOK,  0,POC,  0,  0,  0,VRA,  0,  0,  0,  0,KOR,  0,  0,  0,POC,  0,  0,ZED,
ZED,  0,  0,POC,  0,ZED,STO,ZED,POC,  0,  0,POC,ZED,STO,ZED,  0,POC,  0,  0,ZED,
ZED,  0,  0,POC,  0,ZED,STO,ZED,  0,POC,POC,  0,ZED,STO,ZED,  0,POC,  0,  0,ZED,
ZED,  0,POC,POC,  0,ZED,STO,ZED,  0,POC,POC,  0,ZED,STO,ZED,  0,POC,POC,  0,ZED,
ZED,  0,POC,POC,  0,ZED,STO,ZED,POC,POC,POC,POC,ZED,STO,ZED,  0,POC,POC,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_12_DREAM = {
    .name = "DREAM",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,KRA,  0,ZED,
ZED,  0,KRA,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,KRA,  0,ZED,
ZED,  0,KRA,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,KRA,  0,ZED,
ZED,LOK,KRA,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,KRA,  0,ZED,
ZED,  0,KRA,  0,DOR,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,DOR,  0,KRA,  0,ZED,
ZED,  0,KRA,  0,ZED,ZED,ZED,ZED,ZED,AUT,ZED,ZED,ZED,ZED,ZED,ZED,  0,KRA,  0,ZED,
ZED,  0,KRA,  0,ZED,AUT,AUT,AUT,AUT,  0,AUT,AUT,AUT,AUT,AUT,ZED,  0,KRA,  0,ZED,
ZED,  0,KRA,  0,ZED,AUT,AUT,AUT,AUT,  0,AUT,AUT,AUT,AUT,AUT,ZED,  0,KRA,  0,ZED,
ZED,  0,  0,  0,ZED,AUT,AUT,AUT,AUT,  0,AUT,AUT,AUT,AUT,AUT,ZED,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_13_IDEAL = {
    .name = "IDEAL",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZMR,ZMR,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,JAB,JAB,ZED,
ZED,ZED,ZMR,ZMR,ZMR,ZED,  0,  0,  0,BAL,  0,  0,  0,  0,  0,  0,  0,JAB,JAB,ZED,
ZED,ZED,ZMR,ZMR,ZMR,ZED,  0,  0,BAL,  0,BAL,  0,  0,  0,  0,  0,  0,ZED,ZED,ZED,
ZED,ZED,ZED,ZMR,ZMR,ZED,  0,  0,  0,BAL,  0,ZIR,STO,KOR,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,  0,  0,  0,  0,KRA,STO,ZED,ZED,  0,KRY,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZIR,STO,ZED,ZED,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,KRA,STO,ZED,ZED,ZED,KRY,  0,KRY,  0,  0,  0,  0,DOR,ZED,
ZED,  0,  0,  0,ZIR,STO,ZED,ZED,ZED,KRY,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,ZED,
ZED,  0,  0,STO,ZED,ZED,ZED,KRY,  0,  0,KRY,  0,KRY,  0,KRY,  0,  0,JAB,JAB,ZED,
ZED,  0,KRA,ZED,ZED,  0,  0,  0,KRY,  0,  0,  0,AUT,AUT,AUT,  0,  0,JAB,JAB,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_14_ILUZE = {
    .name = "ILUZE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,BUD,BUD,BUD,  0,BUD,  0,BUD,  0,  0,BUD,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,BUD,  0,  0,BUD,  0,BUD,  0,BUD,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,BUD,  0,  0,BUD,  0,BUD,BUD,  0,  0,  0,BUD,BUD,BUD,  0,  0,  0,  0,ZED,
ZED,  0,BUD,  0,  0,BUD,  0,BUD,  0,BUD,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
VRA,LOK,BUD,  0,  0,BUD,  0,BUD,  0,  0,BUD,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,BUD,BUD,BUD,  0,  0,BUD,  0,  0,BUD,  0,BUD,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,BUD,  0,  0,BUD,  0,BUD,  0,BUD,BUD,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,BUD,  0,  0,BUD,BUD,BUD,  0,BUD,  0,BUD,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,BUD,  0,  0,BUD,  0,BUD,  0,BUD,  0,BUD,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_15_SAINT = {
    .name = "SAINT",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,KRY,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,KOR,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,SLO,STO,SLO,  0,  0,  0,  0,RYB,STO,RYB,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,STO,SLO,STO,  0,ZED,TRE,  0,STO,RYB,STO,ZED,  0,  0,  0,ZED,
ZED,LOK,  0,  0,VRA,ZED,ZED,ZED,POC,JAB,ZED,AUT,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZMR,JAB,ZED,ZMR,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,STO,ZIR,STO,DOR,ZED,ZMR,DOR,STO,KRA,STO,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZIR,STO,ZIR,DOR,DOR,DOR,DOR,KRA,STO,KRA,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_16_BELLS = {
    .name = "BELLS",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,VIN,VIN,VIN,VIN,VIN,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZED,VIN,VIN,VIN,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,LOK,  0,  0,  0,  0,  0,ZED,VRA,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,KRY,ZED,KRY,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,KRY,ZED,KRY,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,KOR,KOR,KOR,KOR,KOR,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_17_TROJA = {
    .name = "TROJA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,KRY,KOR,KRY,KOR,AUT,AUT,AUT,AUT,AUT,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,KOR,KRY,KOR,KRY,ZED,ZED,ZED,ZED,PEN,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,ZED,
ZED,KRY,KOR,ZED,KOR,ZED,PEN,PEN,PEN,PEN,ZED,PEN,PEN,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,KOR,KRY,KOR,KRY,ZED,PEN,ZED,ZED,ZED,ZED,PEN,ZED,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,KRY,KOR,KRY,KOR,ZED,PEN,PEN,PEN,PEN,PEN,PEN,ZED,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,LOK,KRY,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,PEN,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,KRY,KOR,KRY,KOR,ZED,PEN,PEN,PEN,PEN,ZED,PEN,PEN,ZED,ZED,  0,  0,  0,  0,ZED,
ZED,KOR,ZED,ZED,KRY,ZED,PEN,ZED,ZED,PEN,PEN,PEN,PEN,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,KRY,KOR,KRY,KOR,ZED,PEN,PEN,PEN,ZED,ZED,ZED,PEN,PEN,ZED,  0,  0,  0,  0,ZED,
ZED,KOR,KRY,KOR,KRY,ZED,PEN,PEN,PEN,PEN,PEN,PEN,PEN,KOR,ZED,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_18_EMOCE = {
    .name = "EMOCE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,VRA,  0,  0,  0,  0,  0,ZED,
ZED,  0,DOR,  0,  0,ZED,LET,  0,ZED,  0,ZED,  0,LET,ZED,  0,  0,  0,ZMR,  0,ZED,
ZED,  0,DOR,  0,  0,ZED,  0,  0,ZED,  0,ZED,  0,  0,ZED,  0,  0,ZMR,ZMR,  0,ZED,
ZED,  0,DOR,DOR,  0,ZED,ZED,ZED,  0,  0,  0,ZED,ZED,ZED,  0,ZMR,ZMR,ZMR,  0,ZED,
ZED,  0,DOR,DOR,  0,  0,KRY,  0,  0,ZIR,  0,  0,KRY,  0,ZMR,ZMR,ZMR,ZMR,  0,ZED,
ZED,LOK,DOR,DOR,  0,  0,KRY,  0,  0,SLO,  0,  0,KRY,  0,ZMR,ZMR,ZMR,ZMR,  0,ZED,
ZED,  0,DOR,DOR,  0,ZED,ZED,ZED,  0,  0,  0,ZED,ZED,ZED,  0,ZMR,ZMR,ZMR,  0,ZED,
ZED,  0,DOR,  0,  0,ZED,  0,  0,ZED,  0,ZED,  0,  0,ZED,  0,  0,ZMR,ZMR,  0,ZED,
ZED,  0,DOR,  0,  0,ZED,LET,  0,ZED,  0,ZED,  0,LET,ZED,  0,  0,  0,ZMR,  0,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_19_BASTL = {
    .name = "BASTL",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,LOK,KRY,KRY,KRY,KRY,KRY,KRY,VRA,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_20_ZELVA = {
    .name = "ZELVA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,KOR,  0,  0,  0,  0,  0,SLO,SLO,SLO,SLO,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,ZED,  0,  0,  0,  0,ZED,ZED,ZED,ZED,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,KRY,  0,ZED,  0,  0,ZED,STO,ZIR,STO,ZIR,ZED,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,  0,  0,ZED,ZED,STO,ZIR,STO,ZIR,STO,ZIR,ZED,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,  0,  0,STO,ZIR,STO,ZIR,STO,ZIR,STO,ZED,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,  0,ZIR,STO,ZIR,STO,ZIR,STO,ZIR,STO,ZED,KRY,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,ZIR,STO,ZIR,STO,ZIR,STO,ZIR,VRA,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,ZED,
ZED,TRE,JAB,TRE,JAB,TRE,JAB,ZED,ZED,  0,  0,  0,  0,  0,ZED,ZED,  0,JAB,TRE,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_21_JEANS = {
    .name = "JEANS",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,STO,STO,STO,STO,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,STO,STO,STO,STO,ZED,
ZED,  0,POC,  0,  0,  0,ZED,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,POC,  0,ZED,
ZED,BUD,  0,DOR,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,DOR,  0,BUD,ZED,
ZED,ZED,ZED,ZED,ZMR,  0,  0,  0,ZED,  0,  0,ZED,  0,  0,  0,ZMR,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,ZED,ZMR,  0,  0,  0,ZED,ZED,  0,  0,  0,ZMR,ZED,  0,  0,  0,ZED,
ZED,KRY,KRY,  0,  0,ZED,ZMR,  0,  0,LOK,  0,  0,  0,ZMR,ZED,  0,  0,KRY,KRY,ZED,
ZED,KRY,ZED,KRY,  0,  0,ZED,ZMR,  0,VIN,VIN,  0,ZMR,ZED,  0,  0,KRY,ZED,KRY,ZED,
ZED,  0,  0,ZED,KRY,  0,  0,ZED,  0,VIN,VIN,  0,ZED,  0,  0,KRY,ZED,  0,  0,ZED,
ZED,  0,KOR,  0,ZED,KRY,  0,  0,ZED,VIN,VIN,ZED,  0,  0,KRY,ZED,  0,KOR,  0,ZED,
ZED,  0,  0,  0,  0,ZED,KRY,  0,  0,VIN,VIN,  0,  0,KRY,ZED,  0,  0,  0,  0,VRA,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_22_METAL = {
    .name = "METAL",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,LOK,STO,STO,STO,STO,STO,STO,  0,STO,ZED,STO,  0,STO,STO,STO,STO,STO,STO,ZED,
ZED,  0,STO,STO,STO,STO,STO,STO,STO,STO,ZED,STO,STO,STO,STO,STO,STO,STO,STO,ZED,
ZED,STO,STO,STO,STO,STO,STO,  0,STO,  0,ZED,  0,STO,  0,STO,STO,STO,STO,STO,ZED,
ZED,  0,STO,STO,STO,STO,  0,STO,ZED,ZED,ZED,ZED,ZED,STO,  0,STO,  0,STO,STO,ZED,
ZED,STO,STO,STO,STO,  0,ZED,  0,ZED,  0,  0,  0,ZED,  0,ZED,  0,STO,STO,STO,ZED,
ZED,  0,STO,STO,STO,  0,ZED,  0,ZED,  0,RYB,  0,ZED,  0,ZED,  0,STO,STO,STO,ZED,
ZED,  0,  0,STO,  0,  0,ZED,  0,ZED,  0,  0,  0,ZED,  0,ZED,  0,  0,STO,  0,ZED,
ZED,  0,STO,STO,STO,STO,ZED,  0,ZED,ZED,  0,ZED,ZED,  0,ZED,STO,STO,STO,STO,ZED,
ZED,STO,STO,STO,STO,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,STO,STO,STO,ZED,
VRA,  0,STO,  0,STO,  0,ZED,STO,STO,STO,ZIR,STO,STO,STO,ZED,  0,STO,  0,STO,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_23_MIKRO = {
    .name = "MIKRO",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,VIN,VIN,VIN,VIN,  0,  0,VIN,VIN,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,VIN,ZED,ZED,ZED,ZED,VIN,  0,VIN,VIN,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,VIN,ZED,ZED,ZED,ZED,ZED,ZED,VIN,VIN,VIN,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,VIN,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VIN,VIN,  0,  0,  0,  0,  0,  0,ZED,
ZED,LOK,VIN,ZED,ZED,BAL,BAL,BAL,ZED,ZED,ZED,ZED,VIN,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,VIN,ZED,ZED,BAL,LET,BAL,ZMR,ZMR,ZMR,ZED,VIN,  0,STO,  0,STO,  0,STO,ZED,
ZED,  0,VIN,ZED,ZED,BAL,BAL,BAL,ZMR,ZMR,ZMR,ZED,VIN,STO,STO,STO,STO,STO,STO,ZED,
ZED,  0,VIN,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZMR,ZED,VIN,  0,STO,  0,STO,  0,STO,ZED,
ZED,  0,VIN,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,VIN,  0,STO,  0,STO,  0,STO,ZED,
ZED,  0,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,  0,STO,  0,STO,  0,STO,VRA,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_24_SENZA = {
    .name = "SENZA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,TRE,  0,  0,ZED,  0,ZED,  0,  0,  0,ZED,  0,ZED,  0,  0,  0,TRE,  0,ZED,
ZED,  0,TRE,  0,  0,ZED,  0,ZED,  0,  0,  0,ZED,  0,ZED,  0,  0,  0,TRE,  0,ZED,
ZED,ZED,ZED,ZED,  0,ZED,  0,ZED,  0,RYB,  0,ZED,  0,ZED,  0,ZED,ZED,ZED,ZED,ZED,
ZED,  0,TRE,  0,  0,ZED,  0,ZED,  0,ZIR,  0,ZED,  0,ZED,  0,  0,  0,TRE,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,  0,ZED,  0,  0,  0,ZED,  0,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,TRE,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,  0,TRE,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,  0,ZED,ZED,LOK,ZED,ZED,  0,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,TRE,  0,  0,ZED,  0,  0,JAB,  0,JAB,  0,  0,ZED,  0,  0,  0,TRE,  0,ZED,
ZED,  0,  0,  0,  0,ZED,STO,  0,  0,  0,  0,  0,STO,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,TRE,  0,  0,ZED,JAB,JAB,JAB,JAB,JAB,JAB,JAB,ZED,  0,  0,  0,TRE,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_25_GALAX = {
    .name = "GALAX",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,LOK,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,ZED,
ZED,  0,KOR,  0,KOR,  0,KOR,  0,KOR,  0,  0,KOR,  0,KOR,  0,KOR,  0,KOR,  0,ZED,
ZED,ZED,DOR,DOR,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,KRY,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,  0,KOR,  0,  0,KOR,  0,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,DOR,DOR,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_26_STONE = {
    .name = "STONE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,  0,  0,JAB,  0,TRE,  0,ZED,ZED,ZED,ZED,
ZED,ZED,ZIR,SLO,ZIR,ZED,  0,  0,  0,STO,STO,RYB,VIN,JAB,ZED,TRE,  0,ZED,ZED,ZED,
ZED,ZED,SLO,ZIR,SLO,  0,  0,  0,STO,ZED,ZED,STO,RYB,VIN,JAB,ZED,TRE,  0,ZED,ZED,
ZED,ZED,ZIR,SLO,ZIR,  0,  0,STO,ZED,  0,  0,ZED,STO,RYB,VIN,JAB,ZED,TRE,  0,ZED,
ZED,ZED,SLO,ZIR,SLO,  0,STO,ZED,  0,  0,  0,  0,ZED,STO,RYB,VIN,JAB,ZED,  0,ZED,
ZED,ZED,ZED,ZED,  0,STO,ZED,  0,  0,  0,  0,  0,  0,ZED,STO,RYB,VIN,JAB,  0,ZED,
ZED,  0,  0,  0,STO,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,STO,RYB,VIN,JAB,ZED,
ZED,  0,  0,STO,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,STO,RYB,VIN,ZED,
ZED,  0,STO,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,STO,RYB,ZED,
ZED,STO,LOK,ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,VRA,STO,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_27_MINES = {
    .name = "MINES",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,LOK,KRY,ZED,ZED,  0,KRY,  0,  0,ZED,  0,  0,KRY,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,  0,ZED,  0,ZED,KRY,  0,ZED,ZED,ZED,ZED,ZED,  0,ZED,  0,ZED,
ZED,ZED,ZED,  0,ZED,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,
ZED,  0,  0,KRY,  0,  0,ZED,  0,ZED,  0,ZED,ZED,  0,ZED,ZED,  0,KRY,  0,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,KRY,ZED,VRA,ZED,  0,KRY,  0,  0,ZED,  0,ZED,  0,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,ZED,KOR,  0,KRY,  0,ZED,KRY,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,  0,ZED,  0,ZED,ZED,  0,ZED,  0,KRY,ZED,  0,ZED,KRY,KRY,  0,ZED,
ZED,  0,  0,  0,  0,ZED,  0,KRY,  0,ZED,  0,KRY,  0,ZED,  0,KRY,  0,  0,ZED,ZED,
ZED,  0,ZED,ZED,  0,ZED,ZED,  0,  0,  0,ZED,  0,  0,ZED,KRY,  0,  0,ZED,  0,ZED,
ZED,  0,KRY,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_28_FORTE = {
    .name = "FORTE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,VRA,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,  0,ZED,ZIR,ZIR,ZED,  0,  0,ZED,
ZED,  0,ZED,ZIR,ZIR,ZIR,ZIR,ZED,  0,ZED,ZED,  0,ZED,ZIR,ZIR,ZIR,ZIR,ZED,  0,ZED,
ZED,LOK,ZED,ZIR,ZIR,ZIR,  0,  0,  0,SLO,SLO,  0,  0,  0,ZIR,ZIR,ZIR,ZED,  0,ZED,
ZED,  0,ZED,ZIR,ZIR,ZIR,  0,ZIR,SLO,SLO,SLO,SLO,ZED,  0,ZIR,ZIR,ZIR,ZED,  0,ZED,
ZED,  0,ZED,ZIR,ZIR,ZIR,ZIR,ZED,ZED,ZED,ZED,ZED,ZED,ZIR,ZIR,ZIR,ZIR,ZED,  0,ZED,
ZED,  0,  0,ZED,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,  0,ZED,ZIR,ZIR,ZED,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_29_LUCIE = {
    .name = "LUCIE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,
ZED,  0,  0,ZIR,  0,ZED,  0,KRA,  0,  0,ZED,  0,SLO,  0,ZED,  0,ZIR,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,  0,ZED,ZED,ZED,  0,ZED,ZED,LOK,ZED,  0,ZED,ZED,ZED,  0,ZED,ZED,ZED,
ZED,STO,  0,  0,  0,STO,  0,  0,  0,  0,STO,  0,  0,  0,STO,  0,  0,  0,STO,ZED,
ZED,STO,  0,  0,  0,STO,  0,  0,  0,  0,STO,  0,  0,  0,STO,  0,  0,  0,STO,ZED,
ZED,ZED,ZED,  0,ZED,ZED,ZED,  0,ZED,ZED,VRA,ZED,  0,ZED,ZED,ZED,  0,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,
ZED,  0,  0,KRA,  0,ZED,  0,SLO,  0,ZED,  0,  0,ZIR,  0,ZED,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_30_NATUR = {
    .name = "NATUR",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,BUD,BUD,BUD,BUD,BUD,ZED,ZED,KRY,KRY,KRY,KRY,KRY,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,RYB,ZED,RYB,RYB,RYB,ZED,ZED,KOR,KOR,KOR,ZED,KOR,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,ZMR,ZED,ZED,ZMR,ZMR,ZED,ZED,JAB,JAB,ZED,ZED,JAB,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,LET,AUT,ZED,ZED,AUT,ZED,ZED,POC,ZED,ZED,POC,POC,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,DOR,DOR,DOR,ZED,DOR,ZED,ZED,KRA,ZED,KRA,KRA,KRA,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,BAL,BAL,BAL,BAL,BAL,ZED,ZED,VIN,VIN,VIN,VIN,VIN,ZED,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,ZED,STO,STO,ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,  0,  0,ZED,
ZED,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,VRA,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_31_BIENE = {
    .name = "BIENE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,KRY,  0,KRY,  0,KRY,  0,KRY,STO,STO,KRY,  0,KRY,  0,KRY,  0,KRY,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,KRY,  0,KRY,  0,KRY,  0,KRY,STO,STO,KRY,  0,KRY,  0,KRY,  0,KRY,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,LOK,KRY,  0,KRY,  0,KRY,  0,KRY,STO,STO,KRY,  0,KRY,  0,KRY,  0,KRY,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,KRY,  0,KRY,  0,KRY,  0,KRY,STO,STO,KRY,  0,KRY,  0,KRY,  0,KRY,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,KRY,  0,KRY,  0,KRY,  0,KRY,STO,STO,KRY,  0,KRY,  0,KRY,  0,KRY,  0,ZED,
ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_32_KATZE = {
    .name = "KATZE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,ZED,STO,STO,STO,STO,ZED,ZED,STO,STO,STO,STO,ZED,STO,STO,ZED,ZED,
ZED,  0,  0,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,STO,ZED,
ZED,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,ZED,
ZED,STO,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,
ZED,LOK,STO,ZED,ZED,STO,ZED,ZED,STO,ZED,ZED,STO,ZED,ZED,STO,ZED,ZED,STO,ZED,ZED,
ZED,STO,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,
ZED,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,VRA,
ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,ZED,
ZED,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,
ZED,ZED,ZED,STO,STO,STO,STO,ZED,ZED,STO,STO,STO,STO,ZED,ZED,STO,STO,STO,STO,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_33_HYDRO = {
    .name = "HYDRO",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,ZMR,ZED,ZED,ZED,ZMR,  0,  0,DOR,DOR,  0,  0,TRE,TRE,TRE,TRE,  0,  0,ZED,
ZED,  0,ZMR,ZED,ZED,ZED,ZMR,  0,DOR,ZED,ZED,DOR,  0,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,  0,  0,ZMR,ZED,ZMR,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,  0,  0,ZMR,ZED,ZMR,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,LOK,  0,  0,ZMR,  0,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,  0,  0,  0,ZMR,  0,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,TRE,TRE,TRE,  0,  0,VRA,
ZED,  0,  0,ZMR,ZED,ZMR,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,ZED,TRE,  0,  0,  0,ZED,
ZED,  0,  0,ZMR,ZED,ZMR,  0,DOR,ZED,ZED,ZED,ZED,DOR,TRE,ZED,ZED,TRE,  0,  0,ZED,
ZED,  0,ZMR,ZED,ZED,ZED,ZMR,  0,DOR,ZED,ZED,DOR,  0,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,  0,ZMR,ZED,ZED,ZED,ZMR,  0,  0,DOR,DOR,  0,  0,TRE,ZED,ZED,ZED,TRE,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_34_FAUNA = {
    .name = "FAUNA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,VIN,VIN,VIN,VIN,VIN,VIN,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,VIN,VIN,VIN,VIN,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,VIN,VIN,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,VIN,VIN,VIN,VIN,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,VIN,VIN,VIN,VIN,VIN,VIN,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,VIN,VIN,VIN,VIN,VIN,VIN,VIN,VIN,ZED,ZED,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_35_ULTRA = {
    .name = "ULTRA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,KOR,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZED,VRA,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,KRA,  0,ZIR,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,ZED,KRA,KRA,  0,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,ZED,KRA,KRA,KRA,  0,ZIR,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,KRA,KRA,KRA,  0,ZIR,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,ZED,KRA,KRA,  0,ZIR,ZIR,ZED,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,KRA,  0,ZIR,ZED,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,ZED,  0,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,STO,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_36_TODAY = {
    .name = "TODAY",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,LOK,ZED,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,ZED,
ZED,ZED,  0,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,  0,ZED,
ZED,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,  0,KOR,  0,ZED,  0,ZED,
ZED,ZED,  0,KRY,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,ZED,  0,KRY,  0,ZED,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_37_HOROR = {
    .name = "HOROR",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,ZED,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,TRE,JAB,JAB,JAB,TRE,TRE,JAB,JAB,JAB,TRE,ZED,  0,  0,  0,ZED,
ZED,  0,KRY,  0,ZED,TRE,JAB,ZED,JAB,TRE,TRE,JAB,ZED,JAB,TRE,ZED,  0,KRY,  0,ZED,
ZED,  0,  0,  0,ZED,JAB,JAB,ZED,JAB,JAB,JAB,JAB,ZED,JAB,JAB,ZED,  0,  0,  0,ZED,
ZED,LOK,KRY,  0,STO,JAB,ZED,ZED,ZED,JAB,JAB,ZED,ZED,ZED,JAB,STO,  0,KRY,  0,VRA,
ZED,  0,  0,  0,ZED,JAB,JAB,ZED,JAB,JAB,JAB,JAB,ZED,JAB,JAB,ZED,  0,  0,  0,ZED,
ZED,  0,KRY,  0,ZED,TRE,JAB,ZED,JAB,TRE,TRE,JAB,ZED,JAB,TRE,ZED,  0,KRY,  0,ZED,
ZED,  0,  0,  0,ZED,TRE,JAB,JAB,JAB,TRE,TRE,JAB,JAB,JAB,TRE,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_38_GAPPA = {
    .name = "GAPPA",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,STO,  0,  0,STO,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,LET,  0,  0,  0,STO,ZED,STO,STO,ZED,STO,  0,  0,  0,LET,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,STO,ZED,  0,  0,  0,  0,ZED,STO,  0,  0,  0,  0,  0,ZED,
ZED,LOK,  0,  0,  0,STO,ZED,  0,  0,ZED,STO,  0,  0,ZED,STO,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,STO,ZED,  0,  0,  0,ZED,STO,  0,  0,  0,ZED,STO,  0,  0,  0,ZED,
ZED,  0,  0,STO,ZED,STO,  0,STO,  0,  0,ZED,  0,STO,  0,STO,ZED,STO,  0,  0,ZED,
ZED,  0,STO,ZED,  0,  0,ZED,ZED,STO,STO,ZED,STO,ZED,ZED,  0,  0,ZED,STO,  0,ZED,
ZED,  0,ZED,  0,  0,  0,ZED,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,ZED,STO,VRA,
ZED,ZED,  0,  0,  0,  0,ZED,  0,  0,ZED,  0,  0,  0,ZED,  0,  0,  0,  0,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_39_RETAL = {
    .name = "RETAL",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,POC,POC,POC,POC,POC,POC,ZED,  0,  0,POC,POC,POC,POC,POC,POC,POC,ZED,  0,ZED,
ZED,  0,POC,POC,ZED,  0,POC,POC,ZED,  0,  0,POC,POC,ZED,  0,  0,POC,ZED,  0,ZED,
ZED,  0,POC,POC,ZED,  0,POC,POC,ZED,  0,  0,POC,POC,ZED,  0,  0,POC,ZED,  0,ZED,
ZED,  0,POC,POC,ZED,  0,POC,POC,ZED,  0,  0,POC,POC,ZED,POC,ZED,  0,  0,  0,ZED,
ZED,  0,POC,POC,POC,POC,POC,ZED,  0,  0,  0,POC,POC,POC,POC,ZED,  0,  0,  0,ZED,
ZED,  0,POC,POC,ZED,  0,  0,  0,  0,  0,  0,POC,POC,ZED,POC,ZED,  0,  0,  0,ZED,
ZED,  0,POC,POC,ZED,  0,  0,  0,  0,  0,  0,POC,POC,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,POC,POC,ZED,  0,  0,  0,  0,  0,  0,POC,POC,ZED,  0,  0,  0,  0,  0,ZED,
ZED,POC,POC,POC,ZED,ZED,  0,  0,  0,  0,POC,POC,POC,ZED,ZED,  0,  0,  0,  0,VRA,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_40_CLOCK = {
    .name = "CLOCK",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,STO,STO,STO,STO,STO,STO,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,STO,STO,STO,STO,STO,STO,JAB,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,STO,STO,STO,STO,STO,STO,JAB,JAB,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,KRA,KRA,KRA,KRA,KRA,KRA,KRA,JAB,JAB,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,LOK,KRA,KRA,KRA,KRA,KRA,KRA,KRA,JAB,JAB,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,KRA,KRA,KRA,KRA,KRA,KRA,KRA,JAB,JAB,JAB,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,KRA,KRA,KRA,ZED,KRA,KRA,KRA,JAB,JAB,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,KRA,KRA,KRA,KRA,KRA,KRA,KRA,JAB,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,KRA,KRA,KRA,KRA,KRA,KRA,KRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_41_HOMER = {
    .name = "HOMER",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,ZIR,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,SLO,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,  0,  0,ZED,RYB,ZED,RYB,ZED,RYB,ZED,RYB,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,LOK,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_42_BUNNY = {
    .name = "BUNNY",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,ZED,DOR,VRA,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZMR,ZMR,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,  0,ZMR,ZMR,ZMR,ZMR,  0,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,KRA,ZMR,ZMR,ZIR,ZIR,ZIR,ZIR,ZIR,ZIR,ZMR,ZMR,KRA,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,KRA,ZMR,ZMR,SLO,SLO,SLO,SLO,SLO,SLO,ZMR,ZMR,KRA,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,  0,ZMR,ZMR,ZMR,ZMR,  0,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZMR,ZMR,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,DOR,LOK,ZED,ZED,ZED,ZED,ZED,ZED,ZMR,ZMR,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_43_FOTON = {
    .name = "FOTON",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,BUD,  0,  0,  0,RYB,ZED,TRE,  0,  0,  0,JAB,  0,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,BUD,  0,ZED,RYB,ZED,TRE,ZED,  0,JAB,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,BUD,  0,RYB,ZED,TRE,  0,JAB,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,ZED,BUD,RYB,ZED,TRE,JAB,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,LOK,STO,STO,STO,STO,STO,STO,  0,VRA,  0,STO,STO,STO,STO,STO,STO,STO,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,ZED,JAB,TRE,ZED,RYB,BUD,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,ZED,JAB,  0,TRE,ZED,RYB,  0,BUD,ZED,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,ZED,JAB,  0,ZED,TRE,ZED,RYB,ZED,  0,BUD,ZED,ZED,  0,  0,  0,ZED,
ZED,  0,  0,ZED,JAB,  0,ZED,ZED,TRE,ZED,RYB,ZED,ZED,  0,BUD,ZED,  0,  0,  0,ZED,
ZED,  0,  0,JAB,  0,  0,  0,  0,TRE,  0,RYB,  0,  0,  0,  0,BUD,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_44_QUACK = {
    .name = "QUACK",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,  0,STO,STO,  0,ZED,ZED,ZED,ZED,ZED,  0,STO,STO,  0,ZED,ZED,ZED,ZED,ZED,
ZED,  0,STO,ZED,ZED,STO,ZED,ZED,STO,STO,  0,STO,ZED,ZED,STO,  0,STO,STO,  0,ZED,
ZED,STO,ZED,ZED,ZED,  0,STO,STO,  0,  0,STO,  0,ZED,ZED,  0,STO,  0,  0,STO,ZED,
ZED,STO,ZED,  0,STO,STO,STO,ZED,  0,STO,ZED,STO,ZED,  0,STO,ZED,STO,ZED,  0,VRA,
ZED,LOK,ZED,STO,ZED,ZED,STO,ZED,STO,ZED,ZED,STO,ZED,STO,ZED,ZED,STO,ZED,ZED,ZED,
ZED,ZED,ZED,STO,ZED,ZED,STO,ZED,STO,ZED,ZED,STO,ZED,STO,ZED,ZED,STO,ZED,ZED,ZED,
ZED,ZED,ZED,STO,ZED,STO,  0,ZED,STO,ZED,ZED,STO,ZED,STO,ZED,ZED,STO,ZED,ZED,ZED,
ZED,ZED,ZED,  0,STO,  0,ZED,ZED,STO,ZED,STO,  0,ZED,STO,ZED,STO,  0,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,STO,  0,ZED,ZED,  0,STO,  0,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_45_HAFIK = {
    .name = "HAFIK",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,ZMR,ZMR,  0,LOK,  0,  0,DOR,DOR,  0,  0,  0,  0,TRE,TRE,  0,  0,  0,ZED,
ZED,ZMR,ZED,ZED,ZMR,  0,  0,DOR,ZED,ZED,DOR,  0,  0,TRE,ZED,ZED,TRE,  0,  0,ZED,
ZED,ZMR,ZED,ZED,ZMR,  0,  0,DOR,ZED,ZED,DOR,  0,  0,TRE,ZED,ZED,TRE,  0,  0,ZED,
VRA,  0,ZMR,ZMR,  0,  0,  0,  0,DOR,DOR,  0,  0,  0,  0,TRE,TRE,  0,  0,  0,ZED,
ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,
ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,STO,STO,ZED,ZED,ZED,ZED,
ZED,  0,ZMR,ZMR,  0,  0,  0,  0,DOR,DOR,  0,  0,  0,  0,JAB,JAB,  0,  0,  0,ZED,
ZED,ZMR,ZED,ZED,ZMR,  0,  0,DOR,ZED,ZED,DOR,  0,  0,JAB,ZED,ZED,JAB,  0,  0,ZED,
ZED,ZMR,ZED,ZED,ZMR,  0,  0,DOR,ZED,ZED,DOR,  0,  0,JAB,ZED,ZED,JAB,  0,  0,ZED,
ZED,  0,ZMR,ZMR,  0,  0,  0,  0,DOR,DOR,  0,  0,  0,  0,ZED,ZED,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_46_DIZZY = {
    .name = "DIZZY",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,LOK,  0,SLO,  0,ZED,KRA,KRA,ZED,  0,ZIR,  0,ZIR,  0,ZIR,  0,ZED,  0,  0,ZED,
ZED,  0,SLO,  0,SLO,ZED,KRA,ZIR,ZED,  0,  0,SLO,  0,SLO,  0,  0,ZED,STO,RYB,ZED,
ZED,  0,  0,SLO,  0,ZED,KRA,KRA,  0,  0,  0,  0,KRA,  0,  0,  0,  0,  0,  0,ZED,
ZED,SLO,  0,  0,  0,ZED,SLO,KRA,KRA,  0,ZIR,  0,  0,  0,ZIR,  0,ZED,ZED,ZED,ZED,
ZED,  0,SLO,  0,  0,ZED,ZED,ZED,ZED,  0,  0,SLO,  0,SLO,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,  0,SLO,  0,SLO,  0,SLO,  0,ZED,ZED,ZED,ZED,SLO,  0,  0,  0,ZED,
ZED,  0,STO,  0,  0,  0,SLO,  0,SLO,  0,  0,ZIR,ZIR,ZIR,ZED,SLO,SLO,  0,  0,ZED,
ZED,RYB,RYB,ZED,SLO,  0,  0,SLO,  0,  0,  0,  0,ZIR,ZIR,ZED,SLO,SLO,SLO,  0,ZED,
VRA,STO,STO,ZED,  0,SLO,  0,  0,SLO,  0,  0,ZED,ZIR,ZIR,ZED,SLO,SLO,SLO,SLO,ZED,
ZED,RYB,RYB,ZED,SLO,  0,SLO,  0,  0,  0,ZIR,ZED,ZIR,ZIR,ZED,SLO,SLO,SLO,SLO,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_47_STARK = {
    .name = "STARK",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,VIN,  0,  0,  0,  0,  0,  0,  0,VIN,  0,  0,  0,  0,  0,ZED,
ZED,  0,ZED,ZED,ZED,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,AUT,AUT,AUT,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,AUT,AUT,AUT,AUT,  0,ZED,
ZED,  0,ZED,ZED,ZED,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,AUT,AUT,AUT,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,AUT,AUT,AUT,AUT,  0,ZED,
ZED,LOK,ZED,ZED,ZED,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,AUT,AUT,AUT,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,AUT,AUT,AUT,AUT,  0,ZED,
ZED,  0,ZED,ZED,ZED,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,ZED,ZED,ZED,ZED,  0,ZED,
ZED,  0,AUT,AUT,AUT,VIN,ZED,AUT,ZED,LET,ZED,AUT,ZED,VIN,AUT,AUT,AUT,AUT,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,VRA,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_48_ZARAZ = {
    .name = "ZARAZ",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,TRE,ZED,JAB,  0,ZED,ZIR,ZIR,ZIR,ZIR,ZIR,ZIR,ZED,  0,JAB,ZED,TRE,  0,ZED,
ZED,  0,TRE,ZED,JAB,  0,ZED,STO,ZED,KRA,KRA,ZED,STO,ZED,  0,JAB,ZED,TRE,  0,ZED,
ZED,  0,TRE,ZED,JAB,  0,ZED,SLO,SLO,ZED,ZED,SLO,SLO,ZED,  0,JAB,ZED,TRE,  0,ZED,
ZED,LOK,ZED,ZED,ZED,  0,ZMR,SLO,SLO,RYB,RYB,SLO,SLO,ZMR,  0,ZED,ZED,ZED,  0,VRA,
ZED,  0,JAB,ZED,TRE,  0,ZED,SLO,SLO,ZED,ZED,SLO,SLO,ZED,  0,TRE,ZED,JAB,  0,ZED,
ZED,  0,JAB,ZED,TRE,  0,ZED,STO,ZED,KRA,KRA,ZED,STO,ZED,  0,TRE,ZED,JAB,  0,ZED,
ZED,  0,JAB,ZED,TRE,  0,ZED,ZIR,ZIR,ZIR,ZIR,ZIR,ZIR,ZED,  0,TRE,ZED,JAB,  0,ZED,
ZED,  0,  0,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_49_DUKEN = {
    .name = "DUKEN",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,LOK,  0,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,ZED,STO,ZED,ZED,STO,STO,ZED,STO,STO,ZED,STO,STO,ZED,ZED,STO,ZED,  0,ZED,
ZED,  0,ZED,STO,  0,ZED,ZED,STO,ZED,STO,STO,ZED,STO,ZED,ZED,  0,STO,ZED,  0,ZED,
ZED,  0,ZED,LET,STO,  0,ZED,STO,STO,ZED,ZED,STO,STO,ZED,  0,STO,LET,ZED,  0,ZED,
ZED,  0,  0,ZED,LET,STO,  0,STO,STO,ZED,ZED,STO,STO,  0,STO,LET,ZED,  0,  0,ZED,
ZED,  0,  0,  0,ZED,LET,STO,  0,ZED,STO,STO,ZED,  0,STO,LET,ZED,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,LET,STO,ZED,STO,STO,ZED,STO,LET,ZED,  0,  0,  0,  0,ZED,
ZED,  0,KRA,  0,  0,  0,ZED,AUT,AUT,AUT,AUT,AUT,AUT,ZED,  0,  0,  0,KRA,  0,ZED,
ZED,  0,  0,KRA,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,KRA,  0,  0,ZED,
ZED,  0,  0,  0,  0,  0,  0,  0,  0,VRA,ZED,  0,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_50_STORY = {
    .name = "STORY",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,KRY,KOR,STO,JAB,KRA,TRE,RYB,ZIR,ZMR,DOR,POC,AUT,BAL,BUD,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,ZED,ZED,ZED,ZED,ZMR,DOR,ZED,ZED,ZED,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,ZED,TRE,RYB,ZIR,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
VRA,KRY,KOR,STO,JAB,ZED,TRE,RYB,ZIR,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
ZED,LOK,KOR,STO,JAB,ZED,ZED,ZED,ZED,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,KRA,TRE,RYB,ZED,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,KRA,TRE,RYB,ZED,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,ZED,TRE,RYB,ZED,ZMR,DOR,ZED,  0,  0,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,ZED,ZED,ZED,ZED,ZMR,DOR,ZED,ZED,ZED,ZED,SLO,VIN,PEN,LET,ZED,
ZED,KRY,KOR,STO,JAB,KRA,TRE,RYB,ZIR,ZMR,DOR,POC,AUT,BAL,BUD,SLO,VIN,PEN,LET,ZED,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

static vlak_level_t LEVEL_51_SPACE = {
    .name = "SPACE",
    .content = {
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,
ZED,  0,  0,  0,  0,  0,  0,KOR,  0,KOR,  0,KOR,  0,  0,  0,  0,  0,  0,  0,ZED,
ZED,  0,  0,JAB,  0,  0,ZED,KRY,KOR,KRY,KOR,KRY,ZED,  0,  0,JAB,  0,  0,POC,ZED,
ZED,  0,JAB,JAB,JAB,  0,  0,ZED,KRY,KOR,KRY,ZED,  0,  0,JAB,JAB,JAB,  0,ZED,ZED,
ZED,  0,  0,JAB,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,JAB,  0,  0,  0,ZED,
ZED,  0,  0,  0,  0,ZED,ZED,  0,ZED,ZED,ZED,  0,ZED,ZED,  0,  0,  0,  0,POC,ZED,
ZED,  0,  0,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,  0,  0,ZED,ZED,
ZED,  0,TRE,  0,ZED,  0,ZED,ZED,ZED,ZED,ZED,ZED,ZED,  0,ZED,  0,TRE,  0,  0,ZED,
ZED,  0,  0,  0,ZED,  0,ZED,LOK,  0,  0,  0,  0,ZED,  0,ZED,  0,  0,  0,POC,ZED,
ZED,  0,  0,  0,  0,  0,  0,ZED,ZED,  0,ZED,ZED,  0,  0,  0,  0,  0,  0,ZED,ZED,
ZED,STO,  0,STO,  0,STO,  0,STO,  0,STO,  0,STO,  0,STO,  0,STO,  0,STO,  0,VRA,
ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED,ZED
}};

vlak_level_t* vlak_level_array[LEVEL_MAX] = {
    &LEVEL_0_DEMO,
    &LEVEL_1_GOLEM,
    &LEVEL_2_KRONE,
    &LEVEL_3_MYDLO,
    &LEVEL_4_LEDEN,
    &LEVEL_5_STROP,
    &LEVEL_6_LILIE,
    &LEVEL_7_RYBKA,
    &LEVEL_8_KLAUN,
    &LEVEL_9_BRAUN,
    &LEVEL_10_WHITE,
    &LEVEL_11_MOUSE,
    &LEVEL_12_DREAM,
    &LEVEL_13_IDEAL,
    &LEVEL_14_ILUZE,
    &LEVEL_15_SAINT,
    &LEVEL_16_BELLS,
    &LEVEL_17_TROJA,
    &LEVEL_18_EMOCE,
    &LEVEL_19_BASTL,
    &LEVEL_20_ZELVA,
    &LEVEL_21_JEANS,
    &LEVEL_22_METAL,
    &LEVEL_23_MIKRO,
    &LEVEL_24_SENZA,
    &LEVEL_25_GALAX,
    &LEVEL_26_STONE,
    &LEVEL_27_MINES,
    &LEVEL_28_FORTE,
    &LEVEL_29_LUCIE,
    &LEVEL_30_NATUR,
    &LEVEL_31_BIENE,
    &LEVEL_32_KATZE,
    &LEVEL_33_HYDRO,
    &LEVEL_34_FAUNA,
    &LEVEL_35_ULTRA,
    &LEVEL_36_TODAY,
    &LEVEL_37_HOROR,
    &LEVEL_38_GAPPA,
    &LEVEL_39_RETAL,
    &LEVEL_40_CLOCK,
    &LEVEL_41_HOMER,
    &LEVEL_42_BUNNY,
    &LEVEL_43_FOTON,
    &LEVEL_44_QUACK,
    &LEVEL_45_HAFIK,
    &LEVEL_46_DIZZY,
    &LEVEL_47_STARK,
    &LEVEL_48_ZARAZ,
    &LEVEL_49_DUKEN,
    &LEVEL_50_STORY,
    &LEVEL_51_SPACE
};
